---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deploy-cpu-test
  labels:
    app: "cpu-test"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "cpu-test"
  replicas: 1 
  template: 
    metadata:
      labels:
        app: "cpu-test"
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:16.04
        command: ["/bin/dd"]
        args: ["if=/dev/zero", "of=/dev/null"]
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"