apiVersion: v1
kind: Pod
metadata:
  name: coolapp-pod
  labels:
    app: coolapp-pod
spec:
  containers:
  - name: coolapp-pod
    image: codeurjc/kubectl:1.14.3
    command: ['sh', '-c', 'sleep 360000']
  serviceAccountName: myappid