apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  containers:
  - name: mypod
    image: codeurjc/kubectl:1.14.3
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
  serviceAccountName: myserviceaccount