apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myrolebinding
subjects:
- kind: ServiceAccount 
  name: myserviceaccount
roleRef:
  kind: Role
  name: myrole
  apiGroup: rbac.authorization.k8s.io