apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: java-webapp-db-service
    name: anuncios
    namespace: curso-contenedores
  spec:
    ports:
      - name: anuncios-port
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      name: anuncios
    type: ClusterIP
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: anuncios
  spec:
    template: 
      metadata:
        labels:
          name: anuncios
      spec:
        containers:
          - name: anuncios-container
            image: docker-registry.default.svc:5000/curso-contenedores/java-webapp-bbdd:v2
            ports:
              - containerPort: 8080
                protocol: TCP
    replicas: 1 
    triggers:
      - type: ConfigChange
      - type: ImageChange 
        imageChangeParams:
          automatic: true
          containerNames:
            - anuncios-container
          from:
            kind: ImageStreamTag
            name: java-webapp-bbdd:v2
    strategy: 
      type: Rolling
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: java-webapp-db-service 
    name: anuncios
    namespace: curso-contenedores
  spec:
    port:
      targetPort: anuncios-port
    to:
      kind: Service
      name: anuncios
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: java-webapp-bbdd
  spec:
    dockerImageRepository: codeurjc/java-webapp-bbdd
