apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "java-bd.fullname" . }}
  labels:
    app: {{ template "java-bd.name" . }}
    chart: {{ template "java-bd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "java-bd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "java-bd.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysql_root_password }}
          - name: MYSQL_DATABASE
            value: {{ .Values.mysql_database }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
