apiVersion: v1
kind: ServiceAccount
metadata:
  name: webgatos-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgatos-deploy
spec:
  selector:
    matchLabels:
      app: webgatos
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: webgatos
    spec:
      containers:
      - name: webgatos
        image: codeurjc/kubectl:1.14.3
        command: ['sh', '-c', 'kubectl get services; kubectl get pods;']  
      serviceAccountName: webgatos-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: webgatos-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webgatos-rb
  namespace: default
subjects:
- kind: ServiceAccount 
  name: webgatos-sa
roleRef:
  kind: Role
  name: webgatos-role
  apiGroup: rbac.authorization.k8s.io