apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: db
  spec:
    ports:
    - port: 3306
    selector:
      name: mysql
  clusterIP: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mysql-pvc
    namespace: curso-contenedores
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: mysql
  spec:
    template: 
      metadata:
        labels:
          name: mysql
      spec:
        containers:
        - name: mysql-container
          image: docker-registry.default.svc:5000/curso-contenedores/mysql:5.7
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: pass
          - name: MYSQL_DATABASE
            value: test
          ports:
          - containerPort: 3306
            protocol: TCP
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pvc
    replicas: 1 
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - mysql-container
          from:
            kind: ImageStreamTag
            name: mysql:5.7
    strategy: 
      type: Rolling
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: mysql
  spec:
    dockerImageRepository: mysql
