apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo
    app: python-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-port
  clusterIP: None
  selector:
    role: mongo
    app: python-mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-stateful
spec:
  serviceName: mongodb-service
  selector:
    matchLabels: 
      app: python-mongo
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        replicaset: MainRepSet
        app: python-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: pv0001
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---
