version: "3"

services:
  web:
    image: codeurjc/webapp-db-java:v1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/anuncios
      - DATABASE_HOST=db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=anuncios
   
